### ISSUE TITLE
[Bug]: doesn't compile with Apple Swift version 6.2-dev

### ISSUE THREAD

**Issue by cluster2600** [apple/containerization#119]
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

While attempting to compile on macOS 26

### Current behavior

/Users/maxime/Documents/containerization/.build/checkouts/swift-nio/Package.swift:20:14: error: failed to build module 'Foundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.9.904 clang-1700.3.9.904)', while this compiler is 'Apple Swift version 6.2-dev effective-5.10 (LLVM 3c4a54b02dd62b7, Swift a40a7be6945a895)'). Please select a toolchain which matches the SDK.
 18 | // Used only for environment variables, does not make its way
 19 | // into the product code.
 20 | import class Foundation.ProcessInfo
    |              `- error: failed to build module 'Foundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.9.904 clang-1700.3.9.904)', while this compiler is 'Apple Swift version 6.2-dev effective-5.10 (LLVM 3c4a54b02dd62b7, Swift a40a7be6945a895)'). Please select a toolchain which matches the SDK.
 21 | 
 22 | let swiftAtomics: PackageDescription.Target.Dependency = .product(name: "Atomics", package: "swift-atomics")

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Modules/Foundation.swiftmodule/arm64e-apple-macos.swiftinterface: 0:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Modules/Foundation.swiftmodule/arm64e-apple-macos.swiftinterface: 0:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Modules/Foundation.swiftmodule/arm64e-apple-macos.swiftinterface: 0:
error: ExitCode(rawValue: 1)

### Expected Behavior

Compilation should succeed

### Environment

```markdown
- OS: 26 beta 1
- swift: 6.2-dev
- xcode: 26
```

### Relevant log output

```shell
/Users/maxime/Documents/containerization/.build/checkouts/swift-nio/Package.swift:20:14: error: failed to build module 'Foundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.9.904 clang-1700.3.9.904)', while this compiler is 'Apple Swift version 6.2-dev effective-5.10 (LLVM 3c4a54b02dd62b7, Swift a40a7be6945a895)'). Please select a toolchain which matches the SDK.
 18 | // Used only for environment variables, does not make its way
 19 | // into the product code.
 20 | import class Foundation.ProcessInfo
    |              `- error: failed to build module 'Foundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.9.904 clang-1700.3.9.904)', while this compiler is 'Apple Swift version 6.2-dev effective-5.10 (LLVM 3c4a54b02dd62b7, Swift a40a7be6945a895)'). Please select a toolchain which matches the SDK.
 21 | 
 22 | let swiftAtomics: PackageDescription.Target.Dependency = .product(name: "Atomics", package: "swift-atomics")

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Modules/Foundation.swiftmodule/arm64e-apple-macos.swiftinterface: 0:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Modules/Foundation.swiftmodule/arm64e-apple-macos.swiftinterface: 0:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Modules/Foundation.swiftmodule/arm64e-apple-macos.swiftinterface: 0:
error: ExitCode(rawValue: 1)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dkovba** [comment]
Please run `make cross-prep` on the `main` branch. Make sure you have Xcode 26 beta installed, and the active directory is set using `sudo xcode-select -s <PATH_TO_XCODE>`.

**Comment by cluster2600** [comment]
Thanks
